name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Build and test customer service
        run: |
          cd book-store-microservice/customer
          npm ci
          npm run build --if-present
          npm test

      - name: Build and test products service
        run: |
          cd book-store-microservice/products
          npm ci
          npm run build --if-present
          npm test
